### ISSUE TITLE
Fix: mysql maps tinyint(1) to INT64 instead of BOOL

### ISSUE THREAD

**Issue by nevinheintze** [cloudspannerecosystem/harbourbridge#106]
Example issue: active column of customer table in sakila example.

What we get in the spanner schema:

  active INT64 NOT NULL

but we should get:

   active BOOL NOT NULL

Note that mysqldump gives the right mapping.

The issues seems to be in infoschema.go, where we process data from the information_schema.COLUMNS table.
What we get back from the information_schema query for table customer and column active is:
  column_name: active
  data_type: tinyint
  column_type: tinyint(1)
  is_nullable: NO
  column_default: 1
  character_maximum_length: NULL
  numeric_precision: 3
  numeric_scale extra: 0
  
We pass this into toType, and get back the type {Name:tinyint Mods:[] ArrayBounds:[]} i.e. it is missing the mods. Note that toType only looks at data_type and doesn't look at column_type.

**Comment by manitgupta** [comment]
This is working correctly now. 

```
create table tinyint_test (
id int,
tiny tinyint(1),
primary key(id));

insert into tinyint_test(id, tiny) VALUES (2, true);
insert into tinyint_test(id, tiny) VALUES (1, false);
```
![8z2QKLq662VHzLb](https://user-images.githubusercontent.com/6614006/213250803-13033649-b1cd-45dc-b235-76df9c853c1e.png)

![A66vYv5HhxEkWwy](https://user-images.githubusercontent.com/6614006/213250796-ff973727-dc33-4749-a140-8dd329cd20b0.png)
