### ISSUE TITLE
Harbourbridge error while installing

### ISSUE THREAD

**Issue by SchmJohan** [cloudspannerecosystem/harbourbridge#110]
## Expected Behavior

Installation ready to use after command:
```bash
GO111MODULE=on go get github.com/cloudspannerecosystem/harbourbridge
```

## Actual Behavior

Error when running installation command:
```bash
# github.com/lfittl/pg_query_go/parser
In file included from C:\Users\<user>\go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.0\parser\include/c.h:1129,
                 from C:\Users\<user>\go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.0\parser\include/postgres.h:47,
                 from contrib_pgcrypto_sha1.c:50:
C:\Users\<user>\go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.0\parser\include/port.h:17:10: fatal error: netdb.h: No such file or directory
   17 | #include <netdb.h>
      |          ^~~~~~~~~
compilation terminated.
```

## Steps to Reproduce the Problem

1. Install golang on windows
1. Install mingw
1. Install harbourbrige

## Specifications

- Version:
  - go:  go1.15.7 windows/amd64
  - mingw: mingw 10.2.0
  - harbourbridge: latest
- Platform:
  - windows 10

**Comment by nevinheintze** [comment]
Hi Johannes,

Thanks for the detailed bug report. We're working to reproduce the error. This looks to be an issue with the github.com/lfittl/pg_query_go dependency we have -- that library is used to parse pg_dump output. We'll update again shortly. One quick question: where you planning to use HarbourBridge with MySQL or PostgreSQL?

Thanks,

Nevin.

**Comment by nevinheintze** [comment]
Quick update: it appears that mingw doesn't include netdb.h.
See for example https://github.com/msys2/MINGW-packages/issues/3586, and https://www.gnu.org/software/gnulib/manual/html_node/netdb_002eh.html.
We'll update again shortly.

**Comment by nevinheintze** [comment]
One potential workaround is to use WSL2 (available on Windows 10: see https://docs.microsoft.com/en-us/windows/wsl/install-win10), and run HarbourBridge within the Linux subsystem.

**Comment by SchmJohan** [comment]
Hi Nevin,
thanks for the quick response!

> Thanks for the detailed bug report. We're working to reproduce the error. This looks to be an issue with the github.com/lfittl/pg_query_go dependency we have -- that library is used to parse pg_dump output.

> Also, there is an open issue for lfittl/pg_query_go on this: lfittl/pg_query_go#25.

That is also the conclusion I have come to in the meantime!

> One quick question: where you planning to use HarbourBridge with MySQL or PostgreSQL?

I am using Harbourbridge with Postgres / the output of pg_dump.

> One potential workaround is to use WSL2

That is true, though I think my WSL is somewhat broken so I didn´t get that to work.
My workaround right now is to use Harbourbridge in the GCP Cloud Shell.
This works perfectly fine as I am currently just interested in the DDLs and the report, not in Data Migration.

I did stumble upon some more errors while executing Harbourbridge.
The following Error is raised whenever Harbourbridge encounters "))" at the end of an SQL Statement:

```
Generating schema: 60%
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8e55c]
```

I will submit another Issue for this Error.

Thanks for your support,

Johannes

**Comment by nevinheintze** [comment]
Thanks Johannes!
Yes, please file another issue, and include a sample dump file that shows the issue if that is possible. I tried manually editing a pg_dump file and adding  "))" in various combinations with some SQL statements, but only got parse errors (couldn't generate the SIGSEGV panic).

**Comment by manitgupta** [comment]
The only way for Windows is to run Harbourbridge using WSL2
