### ISSUE TITLE
Document caveats with running HarbourBridge server and web UI on different machines

### ISSUE THREAD

**Issue by agasheesh** [cloudspannerecosystem/harbourbridge#112]
When we open a dump file from the web UI, we look for the file on the file system that the server is running on.

If the web UI is running on a browser on the same machine as the server, then all will be good.

But if the web UI is running on a browser on a different machine, this this might be confusing.

For example, an user might run HarbourBridge on their workstation, and then get the web UI up on a browser on their laptop. 

When selecting a file for upload, the user might think it should be a file on their laptop.

Thus, we should document the caveats with running HarbourBridge server and web UI on different machines.

**Comment by shreyakhajanchi** [comment]
UI related caveats have been listed in the UI user guide : https://docs.google.com/document/d/1IfUyxpNhcuSXnCzmEBDXkXVpoiKM4kA-YVt1BcZrdpE/edit#
