### ISSUE TITLE
Broken links under "Example Usage" in the README

### ISSUE THREAD

**Issue by Isabella-Pham** [cloudspannerecosystem/harbourbridge#182]
## Expected Behavior
All of the links under the [Example Usage](https://github.com/cloudspannerecosystem/harbourbridge#example-usage) section in the README should redirect to another page.

## Actual Behavior
All links instead redirect to a 404 Page Not Found Error

## Steps to Reproduce the Problem

1. Go to the [Example Usage](https://github.com/cloudspannerecosystem/harbourbridge#example-usage) section section in the README
2. Press on any link

**Comment by agasheesh** [comment]
Thanks Isabella for reporting this issue. Seems like this was broken by a very recent change. Should be now fixed by https://github.com/cloudspannerecosystem/harbourbridge/pull/183. Can you please try again and see if everything works as expected.
