### ISSUE TITLE
UI: Dropping index undos the schema changes

### ISSUE THREAD

**Issue by Deep1998** [cloudspannerecosystem/harbourbridge#193]
1) Do schema changes in the UI for a table
2) Drop an index for that table.
3) Changes get undone

The drop index option refreshes the table box causing the unsaved changes to be reset. For the user, this can undo alot of changes.

**Comment by shreyakhajanchi** [comment]
This issue is not present in the new HarbourBridge UI. Therefore, closing the issue.
