### ISSUE TITLE
Support to migrate Json column types

### ISSUE THREAD

**Issue by bharadwaj-aditya** [cloudspannerecosystem/harbourbridge#194]
## Actual Behavior
Json is migrated to spanner as a String.

## Expected Behavior
Columns of type Json in source databases (eg-Mysql, Postgres) should be migrated to spanner to columns of Json

Different databases handle Json differently. 
In Postgres, it is implemented as a native column type.
In Mysql 8 and above it is implemented via a check_constraint for Json on top of a longtext 
In Mysql 5.7-8 the representation of the field is different from Mysql 8 (Needs exploration)

**Comment by manitgupta** [comment]
JSON migration is now supported in Harbourbridge.
