### ISSUE TITLE
Consider making data import restartable

### ISSUE THREAD

**Issue by nevinheintze** [cloudspannerecosystem/harbourbridge#20]
To improve reliability of data import, we could keep some state about progress of data writes (say another Spanner table), and restart where we left off. We could take advantage of transactions to know exactly what data was written by an Apply e.g. as part of each Apply batch, we could include info about what rows are included in the batch.

**Comment by bharadwaj-aditya** [comment]
The recommendation for production migrations has been moved to using the Dataflow templates, hence closing this as not required
