### ISSUE TITLE
Support for larger databases

### ISSUE THREAD

**Issue by nevinheintze** [cloudspannerecosystem/harbourbridge#23]
The current HarbourBridge implementation is only intended for databases up to a few GB.
We use a 4GB database pg_dump file regularly for testing.

While the tool can be used for larger DBs, it is not well tested or tuned for that usage. Potential issues are:
a) it could send data too fast to Spanner, especially for single node instances.
b) it could be too slow for large multi-node instances.
c) missing support for restarting import (see https://github.com/cloudspannerecosystem/harbourbridge/issues/20).

**Comment by bharadwaj-aditya** [comment]
The recommendation for production migrations is to use the dataflow templates. Hence closing this as not required
