### ISSUE TITLE
Schema and data default handling

### ISSUE THREAD

**Issue by bharadwaj-aditya** [cloudspannerecosystem/harbourbridge#253]
## Expected Behavior
When a schema-and-data subcommand is used with a session file we should print clean errors that they are unsupported or ignored and exit.

## Actual Behavior
Stacktrace being thrown up with multiple errors

`./harbourbridge schema-and-data -source="mysql" -source-profile="host=localhost,user=abc" -session="session.json" -target-profile="" -skip-foreign-keys=false
**flag provided but not defined: -session**
harbourbridge schema-and-data -source=[source] -target-profile="instance=my-instance"...

Migrate schema and data from source db to target db in schema-and-data. Source db dump
file can be specified by either file param in source-profile or piped to stdin.
Connection profile for source databases in direct connect mode can be specified
by setting appropriate params in source-profile. The schema-and-data flags are:
**./harbourbridge flag redefined: skip-foreign-keys
panic: ./harbourbridge flag redefined: skip-foreign-keys**

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000ae180, {0x1522f10, 0xc000114a00}, {0x13329c5, 0x11}, {0x137ff01, 0xbd})
	/usr/lib/google-golang/src/flag/flag.go:879 +0x2f4
flag.BoolVar(...)
	/usr/lib/google-golang/src/flag/flag.go:638
github.com/cloudspannerecosystem/harbourbridge/cmd.(*SchemaAndDataCmd).SetFlags(0xc0001149c0, 0xc000010020)
	~/harbourbridge/cmd/schema_and_data.go:55 +0x1c5
github.com/google/subcommands.explain({0x1516900, 0xc000010020}, {0x1537058, 0xc0001149c0})
	~/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:308 +0x17d
github.com/google/subcommands.(*Commander).Execute.func1()
	~/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:204 +0x35
flag.(*FlagSet).usage(0xc000114a20)
	/usr/lib/google-golang/src/flag/flag.go:918 +0x22
flag.(*FlagSet).failf(0x7ffd534b6f57, {0x134b1ed, 0x7ffd534b6f57}, {0xc0003e9bc8, 0x40, 0x22d2f40})
	/usr/lib/google-golang/src/flag/flag.go:908 +0x3c
flag.(*FlagSet).parseOne(0xc000114a20)
	/usr/lib/google-golang/src/flag/flag.go:963 +0x332
flag.(*FlagSet).Parse(0xc000114a20, {0xc00003c090, 0xc0003e9cf0, 0xe10291})
	/usr/lib/google-golang/src/flag/flag.go:1005 +0x4f
github.com/google/subcommands.(*Commander).Execute(0xc000057180, {0x152ee10, 0xc0000400b8}, {0x0, 0x0, 0x0})
	/usr/local/google/home/adibh/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:206 +0x35f
github.com/google/subcommands.Execute(...)
	/usr/local/google/home/adibh/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
	/usr/local/google/home/adibh/code/harbourbridge/main.go:112 +0x1f4
`

## Steps to Reproduce the Problem

1. Run a schema-and-data subcommand with -session and -skip-foreign-key flags

**Comment by Deep1998** [comment]
Ran the exact same command, i dont get the stack trace in mine.
![Screenshot 2022-04-22 at 4 16 41 PM](https://user-images.githubusercontent.com/19630018/164700358-95e7ee68-4abc-405f-a440-45e39ad235bd.png)
.
