### ISSUE TITLE
Report of the modifications made by HabourBridge to the schema

### ISSUE THREAD

**Issue by bharadwaj-aditya** [cloudspannerecosystem/harbourbridge#309]
Feature Request: 
Update the Schema report with the changes that HarbourBridge performed during schema migration.

This can be broken down into two problems

1. Explicit changes by User
2. Implicit changes made by HarbourBridge (When the names have invalid characters, non-unique names, syth_id's etc)

**Comment by Deep1998** [comment]
Report when Harbourbridge implicity fix names/ids. Fixing is fine but would be good if it will log those in the report. I noticed it implicitly fixes names/ids if they:
contains invalid characters
starts with bad character
not unique within a schema (Harbourbridge append numbers at the end)
