### ISSUE TITLE
Migration gets stuck in case of incorrect spanner endpoint

### ISSUE THREAD

**Issue by shreyakhajanchi** [cloudspannerecosystem/harbourbridge#324]
In case of an incorrect or unsupported spanner API endpoint the migration seems to be stuck as there is no output in the CLI. The client libraries actually have a default timeout of 60 min therefore the request is retried until the time limit is reached. The user is unaware of any update in the background. We need to add some timeout to these requests to avoid this scenario.

Steps to reproduce:
$gcloud auth application-default login
$export GCLOUD_PROJECT=span-cloud-testing
$export SPANNER_API_ENDPOINT=https://staging-wrenchworks.sandbox.googleapis.com/
$cd harbourbridge
$harbourbridge schema-and-data -source=pg -target-profile="instance=test-instance,dbname=test-db" < ~/singers.pg_dump

source-profile format defaulting to `dump`
Generating schema: 100%
Wrote schema to file 'pg_dump_2022-02-24_f127-4304.schema.txt'.
Wrote legal schema ddl to file 'pg_dump_2022-02-24_f127-4304.schema.ddl.txt'.
Wrote session to file 'pg_dump_2022-02-24_f127-4304.session.json'.
Processed 3203 bytes of pg_dump data (17 statements, 21 rows of data, 0 errors, 0 unexpected conditions).
Schema conversion: EXCELLENT (all columns mapped cleanly).
See file 'pg_dump_2022-02-24_f127-4304.report.txt' for details of the schema and data conversions.
Using Google Cloud project: span-cloud-testing
Using Cloud Spanner instance: test-instance

WARNING: Please check that permissions for this Spanner instance are
appropriate. Spanner manages access control at the database level, and the
database created by HarbourBridge will inherit default permissions from this
instance. All data written to Spanner will be visible to anyone who can
access the created database. Note that pg_dump table-level and row-level
ACLs are dropped during conversion since they are not supported by Spanner.

>>>> HANG <<<<

If the endpoint used is: staging-wrenchworks.sandbox.googleapis.com:443
The above issue doesn't appear.

**Comment by nareshz** [comment]
This issue is coming when we are checking whether the database with dbURI exists or not. We are passing context with no deadline to the function checking this and because of this it is retrying for a default timeout of 60 mins.

> Workaround may be to create a sub context with a timeout of 2 minutes and pass that as context. If context expires before the request is completed then it will generate an error and close out the process.

**Comment by shreyakhajanchi** [comment]
We will have to specify a timeout in the context and see if it solves the purpose

**Comment by nareshz** [comment]
> We will have to specify a timeout in the context and see if it solves the purpose

Okay, I am on it.

**Comment by manitgupta** [comment]
> client libraries actually have a default timeout of 60 min
Client libraries would likely expose a method to override the default timeout while creating the client, we should set this timeout to a value different than 60 mins (as per what is desired in Harbourbridge).

Also, how does the retry logic work in the client library? Does they library provide debug logs on retry?
