### ISSUE TITLE
Observations and issues faced during migration of Hibernate-MySQL app to CloudSpanner

### ISSUE THREAD

**Issue by sunnsing-google** [cloudspannerecosystem/harbourbridge#477]
Creating an umbrella issue to track the problems faced. For the problems worth fixing, more granular issues can be created from the problems described at [doc](https://docs.google.com/document/d/1TejX7UaMZlueAiQ-eWI0MI7DASKq6Sz7W4QMkh2KwyQ/edit?usp=sharing&resourcekey=0-R7Ji3U1Ztbb8bojzPXmOog).

**Comment by manitgupta** [comment]
Broke this into individual issues, closing this bug.
