### ISSUE TITLE
Warning Large number of Foreign keys.

### ISSUE THREAD

**Issue by ricardovieirasantodigital** [cloudspannerecosystem/harbourbridge#494]
Description:
We have detected a high number of foreign keys in the database schema of this project. While foreign keys are an important aspect of database design, excessive use of them can have a negative impact on performance and can make it difficult to maintain the database in the long run.

Having a large number of foreign keys can cause several issues, such as slower query performance, longer transaction times, and increased risk of deadlocks. Additionally, maintaining a complex schema with a large number of foreign keys can make it difficult to add or modify tables and relationships, leading to longer development times and increased risk of errors.

OUT PUT ERROR :
Warning: Large number of foreign keys detected. Spanner can take a long amount of
time to create foreign keys (over 5 mins per batch of Foreign Keys even with no data).
Harbourbridge does not have control over a single foreign key creation time. The number
of concurrent Foreign Key Creation Requests sent to spanner can be increased by
tweaking the MaxWorkers variable

**Comment by manitgupta** [comment]
Hi, @ricardovieirasantodigital,

The above message is just a warning, the foreign key creation would still proceed ahead. Is there any error you are facing?

**Comment by shreyakhajanchi** [comment]
Intended behaviour
