### ISSUE TITLE
Unable to Add Foreign Keys Using ALTER TABLE Statement

### ISSUE THREAD

**Issue by ricardovieirasantodigital** [cloudspannerecosystem/harbourbridge#495]
We have encountered a problem while trying to add foreign keys using the ALTER TABLE statement in this project's database. When attempting to execute the statement, we are receiving an error message indicating that the operation failed.

OUT PUT ERROR MESSAGE: 
117/203Can't add foreign key with statement: ALTER TABLE.

**Comment by manitgupta** [comment]
Hi @ricardovieirasantodigital,

Can you please provide the following information to help us reproduce the issue - 
1. The schema of the migrated table.
2. The name and the details of the foreign key being added.
3. Harbourbridge version (the vX.X.X version or the commitID you are using)
4. The full Harbourbridge command run that is run.

**Comment by shreyakhajanchi** [comment]
Unable to reproduce
